### ISSUE TITLE
How to run project

### ISSUE THREAD

**Issue by alexissahagun1** [monty5811/donate-form#13]
Hi there, I cloned the repo but I can't find a way to make it work. I tried running netlify dev but when I input some number it retrieves an error.
![image](https://user-images.githubusercontent.com/13759190/150090553-bf135aaa-d7b7-49eb-a104-6cc52df9b085.png)

**Comment by monty5811** [comment]
Sorry - this is just a demo repo to accompany a blog post, I don't have the time to provide support for it. It's really only here so people can look at and learn from the code.
